#!/bin/bash -e
# Copyright (C) 2015 Endless Mobile, Inc.
# Licensed under the GPLv2
#
# Note: This is a temporary workaround to transition users from previous
# versions of the OS: codecs placed under /usr/share/EndlessOS/gstreamer-1.0
# will be copied, if needed, to the right place under /var/lib/codecs.
#
# This script will soon be removed in future versions of the OS.

src_dir="/usr/share/EndlessOS/gstreamer-1.0"
dst_dir="/var/lib/codecs/gstreamer-1.0"
mkdir -p ${dst_dir}

# Copy files if they are different or not there yet
src_files="$(ls ${src_dir})"
for file in $src_files; do
    src_file="${src_dir}/${file}"

    # We don't consider directories, only regular files
    [ -f "${src_file}" ] || continue

    dst_file="${dst_dir}/${file}"
    if [ -f "${src_file}" ] && [ ! -f "${dst_file}" ] || ! cmp -s "${src_file}" "${dst_file}"; then
        echo "Copying codec file ${file} to ${dst_dir}..."
        cp -f "${src_file}" "${dst_file}"
    fi
done

exit 0
