#!/bin/bash -e
#
# eos-codecs-install-key: installs an "EOS codecs key" (.eck) to activate codecs
#
# Copyright (C) 2016 Endless Mobile, Inc.
# Authors:
#  Mario Sanchez Prada <mario@endlessm.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

codeckeysdir="/var/lib/codecs/.gnupg/keys.d"

quit_with_code() {
    echo "Press ENTER to exit"
    read
    exit $1
}

if [ $# -lt 1 ]; then
    echo "ERROR: Codec activation file not specified"
    quit_with_code 1
fi

# This directory should be created on boot by the eos-codecs-activate
# service, with the right permissions so regular users can use it.
if [ ! -d ${codeckeysdir} ]; then
    echo "ERROR: No ${codeckeysdir} directory, exiting"
    quit_with_code 1
fi

codeckey_file=${1}
echo "Installing Endless OS Codecs Activation key..."
echo "Key file '${codeckey_file}'"

if cp -f "${codeckey_file}" ${codeckeysdir}/; then
    echo "Endless OS Codec key successfully installed!"
    echo "Please reboot to activate the new codecs"
    quit_with_code 0
fi

echo "An error happened trying to install the codec activation key"
quit_with_code 1
